{
 "title": "JVM Metrics",
 "tags": [
  "bankobserve360",
  "jvm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "JVM heap used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{service}} / {{id}}"
    }
   ]
  },
  {
   "title": "GC pause time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m])",
     "legendFormat": "{{service}} / {{action}}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Class loaded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "jvm_classes_loaded_classes", "legendFormat": "{{service}}" }
   ]
  }
 ]
}